'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmEmpSetTimeByDateRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.frmEmpSetTimeByDateRS", GetType(frmEmpSetTimeByDateRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการยกเลิก กะทั้งเดือนของทุกคน ทุกวันหรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property Cancle_Ka() As String
            Get
                Return ResourceManager.GetString("Cancle_Ka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยกเลิกกะทั้งหมดเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Cancle_Ka_Complete() As String
            Get
                Return ResourceManager.GetString("Cancle_Ka_Complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยกเลิกกะเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Cancle_Ka_Complete2() As String
            Get
                Return ResourceManager.GetString("Cancle_Ka_Complete2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการยกเลิก กะทั้งเดือนของคนนี้หรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property Cancle_Ka2() As String
            Get
                Return ResourceManager.GetString("Cancle_Ka2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกเดือนด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Month() As String
            Get
                Return ResourceManager.GetString("Check_Month", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนปีให้ถูกต้องด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Year() As String
            Get
                Return ResourceManager.GetString("Check_Year", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาไม่มีพนักงานที่ต้องการ กำหนด.
        '''</summary>
        Friend Shared ReadOnly Property Config_Emp() As String
            Get
                Return ResourceManager.GetString("Config_Emp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกกะที่ต้องการ กำหนด.
        '''</summary>
        Friend Shared ReadOnly Property Config_Ka() As String
            Get
                Return ResourceManager.GetString("Config_Ka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกวันที่ที่ต้องการกำหนดกะทำงาน.
        '''</summary>
        Friend Shared ReadOnly Property Config_Ka_Day() As String
            Get
                Return ResourceManager.GetString("Config_Ka_Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บันทึกข้อมูลสำเร็จแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Save_Complete() As String
            Get
                Return ResourceManager.GetString("Save_Complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกรายการที่ต้องการลบด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_Data_For_Del() As String
            Get
                Return ResourceManager.GetString("Select_Data_For_Del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกรายชื่อพนักงานด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_Emp() As String
            Get
                Return ResourceManager.GetString("Select_Emp", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
