'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmLateRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.frmLateRS", GetType(frmLateRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนวันที่ให้ถูกต้องด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Date() As String
            Get
                Return ResourceManager.GetString("Check_Date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาระบุเดือนที่ต้องการจ่ายให้ถูกต้องด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Month() As String
            Get
                Return ResourceManager.GetString("Check_Month", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนตัวเลขให้ถูกต้องด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Number() As String
            Get
                Return ResourceManager.GetString("Check_Number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่ที่ป้อนอยู่นอกรอบเดือน กรุณาป้อนใหม่ วันที่สิ้นสุด ไม่ควรเกินกว่าวันที่ 10 ของเดือนที่เลือก.
        '''</summary>
        Friend Shared ReadOnly Property Dat_Out_Month_Stop() As String
            Get
                Return ResourceManager.GetString("Dat_Out_Month_Stop", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่ที่ป้อนอยู่นอกรอบเดือน กรุณาป้อนใหม่ วันที่เริ่ม ไม่ควรน้อยกว่าวันที่ 11 ของเดือนก่อนหน้า.
        '''</summary>
        Friend Shared ReadOnly Property Dat_Out_Month_Strat() As String
            Get
                Return ResourceManager.GetString("Dat_Out_Month_Strat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่พบข้อมูล.
        '''</summary>
        Friend Shared ReadOnly Property Data_NotFound() As String
            Get
                Return ResourceManager.GetString("Data_NotFound", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการลบข้อมูลสายทั้งหมดหรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property Del_Late() As String
            Get
                Return ResourceManager.GetString("Del_Late", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลบข้อมูลเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Delete_Complete() As String
            Get
                Return ResourceManager.GetString("Delete_Complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่มีข้อมูลที่จะบันทึก.
        '''</summary>
        Friend Shared ReadOnly Property NoData_To_Save() As String
            Get
                Return ResourceManager.GetString("NoData_To_Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บันทึกข้อมูลสำเร็จแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Save_Complete() As String
            Get
                Return ResourceManager.GetString("Save_Complete", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
