'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmTimeworkRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.frmTimeworkRS", GetType(frmTimeworkRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณากรอกวันที่ให้ถูกต้องด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Date() As String
            Get
                Return ResourceManager.GetString("Check_Date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนรหัสพนักงานในช่องค้นหาก่อน.
        '''</summary>
        Friend Shared ReadOnly Property Insert_EmpID() As String
            Get
                Return ResourceManager.GetString("Insert_EmpID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนชื่อไฟล์ด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Insert_FineName() As String
            Get
                Return ResourceManager.GetString("Insert_FineName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประมวลผลเสร็จเรียบร้อย.
        '''</summary>
        Friend Shared ReadOnly Property Process_Complete() As String
            Get
                Return ResourceManager.GetString("Process_Complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to การบันทึกข้อมูลอัตโนมัติจะทำการเคลียร์ข้อมูลเก่าทิ้งทั้งหมดแล้วเพิ่มเวลาเข้างาน/ออกงาน ให้อัตโนมัติตามวันที่ที่กำหนดไว้ข้างบน.
        '''</summary>
        Friend Shared ReadOnly Property Save_Data_Auto() As String
            Get
                Return ResourceManager.GetString("Save_Data_Auto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Success() As String
            Get
                Return ResourceManager.GetString("Success", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
