'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class frmVacationRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.frmVacationRS", GetType(frmVacationRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนวันที่ให้ถูกต้องด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Date() As String
            Get
                Return ResourceManager.GetString("Check_Date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนชม.ที่ชดเชยไม่ควร 4 ชม.กรุณาตรวจสอบด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Hour() As String
            Get
                Return ResourceManager.GetString("Check_Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการลบข้อมูลที่เลือกไว้จริงๆ หรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property Confirm_Del() As String
            Get
                Return ResourceManager.GetString("Confirm_Del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลบข้อมูลเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Delete_Complete() As String
            Get
                Return ResourceManager.GetString("Delete_Complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันสุดท้ายน้อยกว่าวันที่เริ่มต้นกรุณากรอกใหม่.
        '''</summary>
        Friend Shared ReadOnly Property Insert_Data_Again() As String
            Get
                Return ResourceManager.GetString("Insert_Data_Again", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนรหัสพนักงานด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Insert_EmpID() As String
            Get
                Return ResourceManager.GetString("Insert_EmpID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มีข้อมูลอยู่แล้วคุณต้องการเขียนข้อมูลทับหรือเปล่า.
        '''</summary>
        Friend Shared ReadOnly Property Repleace_Data() As String
            Get
                Return ResourceManager.GetString("Repleace_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มีข้อมูลอยู่ในระหว่างช่วงที่กำหนด คุณต้องการเขียนข้อมูลทับหรือเปล่า.
        '''</summary>
        Friend Shared ReadOnly Property Repleace_Data_2() As String
            Get
                Return ResourceManager.GetString("Repleace_Data_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลได้เนื่องจากสิทธิในการลาหมด.
        '''</summary>
        Friend Shared ReadOnly Property Save_Failed() As String
            Get
                Return ResourceManager.GetString("Save_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลได้เนื่องจากสิทธิในการลาหมด เนื่องจากช่วงเวลาที่กำหนดเกินสิทธิที่ได้กำหนดไว้.
        '''</summary>
        Friend Shared ReadOnly Property Save_Failed_Vacation() As String
            Get
                Return ResourceManager.GetString("Save_Failed_Vacation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกข้อมูลที่ต้องการลบด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_Del() As String
            Get
                Return ResourceManager.GetString("Select_Del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกประเภทการลาด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_Vacation() As String
            Get
                Return ResourceManager.GetString("Select_Vacation", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
