'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class cryCountAbsentRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.cryCountAbsentRS", GetType(cryCountAbsentRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;สรุปจำนวนพนักงาน การลาขาดสาย&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Abstract_Absent() As String
            Get
                Return ResourceManager.GetString("Abstract_Absent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;พนง.ลา,ขาด,สาย&apos;+chr(13)+&apos;(คน)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Cal_Abs() As String
            Get
                Return ResourceManager.GetString("Cal_Abs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;แผนก&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Dep() As String
            Get
                Return ResourceManager.GetString("Dep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ฝ่าย&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Div() As String
            Get
                Return ResourceManager.GetString("Div", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ผู้ตรวจสอบ :&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Examiner() As String
            Get
                Return ResourceManager.GetString("Examiner", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รายงานลาขาดสายของพนักงานประจำวันที่ &apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head() As String
            Get
                Return ResourceManager.GetString("rpt_head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;หน่วย&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Sec() As String
            Get
                Return ResourceManager.GetString("Sec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ขาด&apos;+chr(13)+&apos;(คน)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_Absent() As String
            Get
                Return ResourceManager.GetString("T_Absent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;สาย&apos;+chr(13)+&apos;(คน)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_Late() As String
            Get
                Return ResourceManager.GetString("T_Late", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ลา &apos;+chr(13)+&apos;(คน)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Vac() As String
            Get
                Return ResourceManager.GetString("Vac", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
