'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class cryRPT_MaxOTRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.cryRPT_MaxOTRS", GetType(cryRPT_MaxOTRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;วัน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Day() As String
            Get
                Return ResourceManager.GetString("Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ฝ่าย/&apos;+chr(13)+&apos;แผนก/ตำแหน่ง&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Div() As String
            Get
                Return ResourceManager.GetString("Div", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ม.ค.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M1() As String
            Get
                Return ResourceManager.GetString("M1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ต.ค.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M10() As String
            Get
                Return ResourceManager.GetString("M10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;พ.ย.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M11() As String
            Get
                Return ResourceManager.GetString("M11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ธ.ค.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M12() As String
            Get
                Return ResourceManager.GetString("M12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ก.พ.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M2() As String
            Get
                Return ResourceManager.GetString("M2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;มี.ค.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M3() As String
            Get
                Return ResourceManager.GetString("M3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;เม.ย.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M4() As String
            Get
                Return ResourceManager.GetString("M4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;พ.ค.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M5() As String
            Get
                Return ResourceManager.GetString("M5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;มิ.ย.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M6() As String
            Get
                Return ResourceManager.GetString("M6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ก.ค.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M7() As String
            Get
                Return ResourceManager.GetString("M7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ส.ค.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M8() As String
            Get
                Return ResourceManager.GetString("M8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ก.ย.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M9() As String
            Get
                Return ResourceManager.GetString("M9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ชั่วโมง O.T. สูงสุด/วัน/สัปดาห์  ปี  &apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head() As String
            Get
                Return ResourceManager.GetString("rpt_head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รวมทั้งสิ้น&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_all() As String
            Get
                Return ResourceManager.GetString("T_all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รวมส่วนงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_work() As String
            Get
                Return ResourceManager.GetString("T_work", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ส/ด&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Week() As String
            Get
                Return ResourceManager.GetString("Week", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
