'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class crySumaryWagePerDayRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.crySumaryWagePerDayRS", GetType(crySumaryWagePerDayRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;คน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property emp() As String
            Get
                Return ResourceManager.GetString("emp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ประจำวัน 01/08/2012&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Header() As String
            Get
                Return ResourceManager.GetString("Header", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ชม.ปกติ&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Hour() As String
            Get
                Return ResourceManager.GetString("Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เงินชม.ปกติ&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M_Hour() As String
            Get
                Return ResourceManager.GetString("M_Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;เงิน ชม.OT&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M_OT() As String
            Get
                Return ResourceManager.GetString("M_OT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;OT&apos;.
        '''</summary>
        Friend Shared ReadOnly Property OT() As String
            Get
                Return ResourceManager.GetString("OT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ใบรายงานค่าแรง&apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head() As String
            Get
                Return ResourceManager.GetString("rpt_head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รวมทั้งหมด&apos;.
        '''</summary>
        Friend Shared ReadOnly Property S_Total() As String
            Get
                Return ResourceManager.GetString("S_Total", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รวมเงิน&apos;+chr(13)+&apos;ชม.ปกติ/OT&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Total_H_OT() As String
            Get
                Return ResourceManager.GetString("Total_H_OT", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
