'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class cryTimeAbsentRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.cryTimeAbsentRS", GetType(cryTimeAbsentRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ขาดงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Abs() As String
            Get
                Return ResourceManager.GetString("Abs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ถึงวันที่&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Date_To() As String
            Get
                Return ResourceManager.GetString("Date_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ระหว่างวันที่&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Datestart() As String
            Get
                Return ResourceManager.GetString("Datestart", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;DDS&apos;.
        '''</summary>
        Friend Shared ReadOnly Property DDSName() As String
            Get
                Return ResourceManager.GetString("DDSName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;พนง.&apos;+chr(13)+&apos;ไม่มาทำงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Emp_Abs() As String
            Get
                Return ResourceManager.GetString("Emp_Abs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;จน.พนักงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Emp_Amt() As String
            Get
                Return ResourceManager.GetString("Emp_Amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;%ของพนง.&apos;+chr(13)+&apos;ไม่มาทำงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Per_Emp_abs() As String
            Get
                Return ResourceManager.GetString("Per_Emp_abs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;จำนวนพนักงานไม่มาทำงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head() As String
            Get
                Return ResourceManager.GetString("rpt_head", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
