'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class cryTimeworkSummarizeRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.cryTimeworkSummarizeRS", GetType(cryTimeworkSummarizeRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ครั้ง&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Amt() As String
            Get
                Return ResourceManager.GetString("Amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ลำดับ&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Col() As String
            Get
                Return ResourceManager.GetString("Col", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ถึงวันที่ &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Date_To() As String
            Get
                Return ResourceManager.GetString("Date_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;วัน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Day() As String
            Get
                Return ResourceManager.GetString("Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;แผนก : &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Dep() As String
            Get
                Return ResourceManager.GetString("Dep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ฝ่าย : &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Div() As String
            Get
                Return ResourceManager.GetString("Div", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;พนักงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Emp() As String
            Get
                Return ResourceManager.GetString("Emp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;พนักงานจำนวน &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Emp_Amt() As String
            Get
                Return ResourceManager.GetString("Emp_Amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ช.ม.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Hour() As String
            Get
                Return ResourceManager.GetString("Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รหัส&apos;.
        '''</summary>
        Friend Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;คน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property kon() As String
            Get
                Return ResourceManager.GetString("kon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;สาย&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Late() As String
            Get
                Return ResourceManager.GetString("Late", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;นาที&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Min() As String
            Get
                Return ResourceManager.GetString("Min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ชื่อ - นามสกุล&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Name_Last() As String
            Get
                Return ResourceManager.GetString("Name_Last", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รายงานเวลาการทำงานของพนักงาน(แบบสรุป) ระหว่างวันที่&apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head_strat() As String
            Get
                Return ResourceManager.GetString("rpt_head_strat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;หน่วยงาน : &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Sec() As String
            Get
                Return ResourceManager.GetString("Sec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รวมเวลา&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_Time() As String
            Get
                Return ResourceManager.GetString("T_Time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ทำงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Work() As String
            Get
                Return ResourceManager.GetString("Work", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
