'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class HTFReportForm
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.HTFReportForm", GetType(HTFReportForm).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานพนักงานขาดงาน ประจำวันที่  .
        '''</summary>
        Friend Shared ReadOnly Property HTFcryAbsentByEmp() As String
            Get
                Return ResourceManager.GetString("HTFcryAbsentByEmp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานการลาขาดสายของพนักงาน ประจำวันที่   .
        '''</summary>
        Friend Shared ReadOnly Property HTFcryCountAbsent() As String
            Get
                Return ResourceManager.GetString("HTFcryCountAbsent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงาน ชั่วโมง O.T. สูงสุด/วัน/สัปดาห์  ประจำปี.
        '''</summary>
        Friend Shared ReadOnly Property HTFcryRPT_MaxOT() As String
            Get
                Return ResourceManager.GetString("HTFcryRPT_MaxOT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานค่าล่วงเวลาทำงาน (ตามช่วงเวลา).
        '''</summary>
        Friend Shared ReadOnly Property HTFcryRPT_OTreport() As String
            Get
                Return ResourceManager.GetString("HTFcryRPT_OTreport", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานสรุปการหยุดงานประจำปี.
        '''</summary>
        Friend Shared ReadOnly Property HTFcryRPT_SummarizeVacationByYear_Config() As String
            Get
                Return ResourceManager.GetString("HTFcryRPT_SummarizeVacationByYear_Config", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานสรุปการหยุดงานประจำปี.
        '''</summary>
        Friend Shared ReadOnly Property HTFcryRPT_SummarizeVacationByYear_Config2() As String
            Get
                Return ResourceManager.GetString("HTFcryRPT_SummarizeVacationByYear_Config2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนพนักงานไม่มาทำงาน.
        '''</summary>
        Friend Shared ReadOnly Property HTFcryTimeAbsent() As String
            Get
                Return ResourceManager.GetString("HTFcryTimeAbsent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงาน มาสาย/ลา/ขาด ของพนักงาน(แบบสรุป).
        '''</summary>
        Friend Shared ReadOnly Property HTFcryTimeAbsLate() As String
            Get
                Return ResourceManager.GetString("HTFcryTimeAbsLate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานการทำงานของพนักงาน(แบบสรุป).
        '''</summary>
        Friend Shared ReadOnly Property HTFcryTimeworkSummarize() As String
            Get
                Return ResourceManager.GetString("HTFcryTimeworkSummarize", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บัญชีลงเวลาทำงาน.
        '''</summary>
        Friend Shared ReadOnly Property HTFrptCheckComing() As String
            Get
                Return ResourceManager.GetString("HTFrptCheckComing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บัญชีลงเวลาทำงาน.
        '''</summary>
        Friend Shared ReadOnly Property HTFrptEmpTimeINOUT() As String
            Get
                Return ResourceManager.GetString("HTFrptEmpTimeINOUT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานการทำงานของพนักงาน (แบบละเอียด).
        '''</summary>
        Friend Shared ReadOnly Property HTFrptEmpTimeWork_Detail() As String
            Get
                Return ResourceManager.GetString("HTFrptEmpTimeWork_Detail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานการทำงานของพนักงาน (แบบที่ 2).
        '''</summary>
        Friend Shared ReadOnly Property HTFrptEmpTimeWork_Detail_2() As String
            Get
                Return ResourceManager.GetString("HTFrptEmpTimeWork_Detail_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สรุปยอดประจำเดือน.
        '''</summary>
        Friend Shared ReadOnly Property HTFrptSumary() As String
            Get
                Return ResourceManager.GetString("HTFrptSumary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานสรุปยอด สาย - ขาด (บาท) รายเดือน.
        '''</summary>
        Friend Shared ReadOnly Property HTFrptTimeSumAbsLateByMonth() As String
            Get
                Return ResourceManager.GetString("HTFrptTimeSumAbsLateByMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานตารางการทำงาน.
        '''</summary>
        Friend Shared ReadOnly Property HTFrptTimeTableByMonth() As String
            Get
                Return ResourceManager.GetString("HTFrptTimeTableByMonth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to รายงานทำงานปกติ + ชั่วโมง O.T. / ต่อสัปดาห์.
        '''</summary>
        Friend Shared ReadOnly Property OTByWeek() As String
            Get
                Return ResourceManager.GetString("OTByWeek", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
