'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class MonthLang
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.MonthLang", GetType(MonthLang).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มกราคม .
        '''</summary>
        Friend Shared ReadOnly Property M1() As String
            Get
                Return ResourceManager.GetString("M1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ตุลาคม .
        '''</summary>
        Friend Shared ReadOnly Property M10() As String
            Get
                Return ResourceManager.GetString("M10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to พฤศจิกายน .
        '''</summary>
        Friend Shared ReadOnly Property M11() As String
            Get
                Return ResourceManager.GetString("M11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ธันวาคม .
        '''</summary>
        Friend Shared ReadOnly Property M12() As String
            Get
                Return ResourceManager.GetString("M12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กุมภาพันธ์ .
        '''</summary>
        Friend Shared ReadOnly Property M2() As String
            Get
                Return ResourceManager.GetString("M2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มีนาคม .
        '''</summary>
        Friend Shared ReadOnly Property M3() As String
            Get
                Return ResourceManager.GetString("M3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เมษายน .
        '''</summary>
        Friend Shared ReadOnly Property M4() As String
            Get
                Return ResourceManager.GetString("M4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to พฤษภาคม .
        '''</summary>
        Friend Shared ReadOnly Property M5() As String
            Get
                Return ResourceManager.GetString("M5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มิถุนายน .
        '''</summary>
        Friend Shared ReadOnly Property M6() As String
            Get
                Return ResourceManager.GetString("M6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรกฏาคม .
        '''</summary>
        Friend Shared ReadOnly Property M7() As String
            Get
                Return ResourceManager.GetString("M7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สิงหาคม .
        '''</summary>
        Friend Shared ReadOnly Property M8() As String
            Get
                Return ResourceManager.GetString("M8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กันยายน .
        '''</summary>
        Friend Shared ReadOnly Property M9() As String
            Get
                Return ResourceManager.GetString("M9", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to พ.ศ. .
        '''</summary>
        Friend Shared ReadOnly Property PS() As String
            Get
                Return ResourceManager.GetString("PS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 543.
        '''</summary>
        Friend Shared ReadOnly Property Year() As String
            Get
                Return ResourceManager.GetString("Year", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
