'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rptCheckComingRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.rptCheckComingRS", GetType(rptCheckComingRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ลำดับ&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Col() As String
            Get
                Return ResourceManager.GetString("Col", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รหัสพนักงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property EmpCode() As String
            Get
                Return ResourceManager.GetString("EmpCode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ผู้จัดการ&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Manager() As String
            Get
                Return ResourceManager.GetString("Manager", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ชื่อ - สกุล&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Name_Last() As String
            Get
                Return ResourceManager.GetString("Name_Last", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;หมายเหตุ&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Remark() As String
            Get
                Return ResourceManager.GetString("Remark", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;บัญชีลงเวลาการปฏิบัติงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head() As String
            Get
                Return ResourceManager.GetString("rpt_head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ลายเซ็น&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Signature() As String
            Get
                Return ResourceManager.GetString("Signature", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;เวลามา&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_in() As String
            Get
                Return ResourceManager.GetString("T_in", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;เวลากลับ&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_out() As String
            Get
                Return ResourceManager.GetString("T_out", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
