'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rptEmpTimeWork_Detail_2RS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.rptEmpTimeWork_Detail_2RS", GetType(rptEmpTimeWork_Detail_2RS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;วัน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Day() As String
            Get
                Return ResourceManager.GetString("Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;แผนก :&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Dep() As String
            Get
                Return ResourceManager.GetString("Dep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ฝ่าย :&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Div() As String
            Get
                Return ResourceManager.GetString("Div", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;วันที่&apos;.
        '''</summary>
        Friend Shared ReadOnly Property DT() As String
            Get
                Return ResourceManager.GetString("DT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Holiday&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Holiday() As String
            Get
                Return ResourceManager.GetString("Holiday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ชม.&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Hour() As String
            Get
                Return ResourceManager.GetString("Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รหัส &apos;.
        '''</summary>
        Friend Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;เข้า&apos;.
        '''</summary>
        Friend Shared ReadOnly Property In_Text() As String
            Get
                Return ResourceManager.GetString("In_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;กะ &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Ka() As String
            Get
                Return ResourceManager.GetString("Ka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Late&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Late() As String
            Get
                Return ResourceManager.GetString("Late", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Leave&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Leave() As String
            Get
                Return ResourceManager.GetString("Leave", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชื่อ-นามสกุล&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Name_Last() As String
            Get
                Return ResourceManager.GetString("Name_Last", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;Normal&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Normal() As String
            Get
                Return ResourceManager.GetString("Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;OT&apos;.
        '''</summary>
        Friend Shared ReadOnly Property OT() As String
            Get
                Return ResourceManager.GetString("OT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ออก&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Out() As String
            Get
                Return ResourceManager.GetString("Out", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ลำดับ&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Rec() As String
            Get
                Return ResourceManager.GetString("Rec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รายงานเวลาการทำงานของพนักงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head() As String
            Get
                Return ResourceManager.GetString("rpt_head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;หน่วย :&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Sec() As String
            Get
                Return ResourceManager.GetString("Sec", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
