'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rptEmpTimeINOUTRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.rptEmpTimeINOUTRS", GetType(rptEmpTimeINOUTRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ประจำวันที่ : &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Date_St() As String
            Get
                Return ResourceManager.GetString("Date_St", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;วันที่&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Date_Text() As String
            Get
                Return ResourceManager.GetString("Date_Text", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;  ถึง  &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Date_To() As String
            Get
                Return ResourceManager.GetString("Date_To", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;แผนก : &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Dep() As String
            Get
                Return ResourceManager.GetString("Dep", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รหัสพนง. : &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Emp_ID() As String
            Get
                Return ResourceManager.GetString("Emp_ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;สาย&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Late() As String
            Get
                Return ResourceManager.GetString("Late", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;สาย(฿)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property M_Late() As String
            Get
                Return ResourceManager.GetString("M_Late", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ออกก่อน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property O_Before() As String
            Get
                Return ResourceManager.GetString("O_Before", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รายงานเวลา/ทำงาน/สาย/ออกก่อน ของพนักงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head() As String
            Get
                Return ResourceManager.GetString("rpt_head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;เวลาเข้า&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_In() As String
            Get
                Return ResourceManager.GetString("T_In", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รวมสาย&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_Late() As String
            Get
                Return ResourceManager.GetString("T_Late", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;เวลาออก&apos;.
        '''</summary>
        Friend Shared ReadOnly Property T_Out() As String
            Get
                Return ResourceManager.GetString("T_Out", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
