'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class rptTimeSumAbsLateByMonthRS
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.rptTimeSumAbsLateByMonthRS", GetType(rptTimeSumAbsLateByMonthRS).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ขาดงาน&apos;+chr(13)+&apos;(วัน)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Abs() As String
            Get
                Return ResourceManager.GetString("Abs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ขาด&apos;+chr(13)+&apos;(บาท)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Abs_B() As String
            Get
                Return ResourceManager.GetString("Abs_B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประจำเดือน  .
        '''</summary>
        Friend Shared ReadOnly Property Head_Date() As String
            Get
                Return ResourceManager.GetString("Head_Date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;แผนก : &apos;.
        '''</summary>
        Friend Shared ReadOnly Property Head_Dept() As String
            Get
                Return ResourceManager.GetString("Head_Dept", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รหัส&apos;.
        '''</summary>
        Friend Shared ReadOnly Property ID() As String
            Get
                Return ResourceManager.GetString("ID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;สาย&apos;+chr(13)+&apos;(บาท)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Late_B() As String
            Get
                Return ResourceManager.GetString("Late_B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;สาย&apos;+chr(13)+&apos;(วัน)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Late_D() As String
            Get
                Return ResourceManager.GetString("Late_D", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;กลับก่อน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property LateOut() As String
            Get
                Return ResourceManager.GetString("LateOut", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;กลับก่อน&apos;+chr(13)+&apos;(บาท)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property LateOut_B() As String
            Get
                Return ResourceManager.GetString("LateOut_B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ชื่อ - สกุล&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Name_Last() As String
            Get
                Return ResourceManager.GetString("Name_Last", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ลำดับที่&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Rec() As String
            Get
                Return ResourceManager.GetString("Rec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;ตารางวันทำงาน&apos;.
        '''</summary>
        Friend Shared ReadOnly Property rpt_head() As String
            Get
                Return ResourceManager.GetString("rpt_head", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รวมยอดหัก&apos;+chr(13)+&apos;(บาท)&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Total_B() As String
            Get
                Return ResourceManager.GetString("Total_B", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos;รวมทั้งหมด&apos;.
        '''</summary>
        Friend Shared ReadOnly Property Total_Text() As String
            Get
                Return ResourceManager.GetString("Total_Text", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
