'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class res_warning_message_spacial
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.res_warning_message_spacial", GetType(res_warning_message_spacial).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จน.ชม.ทำงานควรมากกว่า 0.
        '''</summary>
        Friend Shared ReadOnly Property Amount_hr_over_zero() As String
            Get
                Return ResourceManager.GetString("Amount_hr_over_zero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการประมวลผลเวลาทำงานจริงหรือไม่?.
        '''</summary>
        Friend Shared ReadOnly Property Ask_Procress() As String
            Get
                Return ResourceManager.GetString("Ask_Procress", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการยกเลิก กะทั้งเดือนของทุกคน ทุกวันหรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property Cancle_Ka() As String
            Get
                Return ResourceManager.GetString("Cancle_Ka", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยกเลิกกะทั้งหมดเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Cancle_Ka_Complete() As String
            Get
                Return ResourceManager.GetString("Cancle_Ka_Complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยกเลิกกะเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Cancle_Ka_Complete2() As String
            Get
                Return ResourceManager.GetString("Cancle_Ka_Complete2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการยกเลิก กะทั้งเดือนของคนนี้หรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property Cancle_Ka2() As String
            Get
                Return ResourceManager.GetString("Cancle_Ka2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่เริ่มควรป้อนได้ตั้งแต่วันที่ 1-28 เท่านั้น.
        '''</summary>
        Friend Shared ReadOnly Property Check_Date_Start() As String
            Get
                Return ResourceManager.GetString("Check_Date_Start", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่เริ่มควรป้อนได้ตั้งแต่วันที่ 1-28 เท่านั้น *** ถ้าต้องการสิ้นเดือนก็ติ๊กที่ ถึงสิ้นเดือน แทน.
        '''</summary>
        Friend Shared ReadOnly Property Check_Date_Start2() As String
            Get
                Return ResourceManager.GetString("Check_Date_Start2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนวันหยุดด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Holiday() As String
            Get
                Return ResourceManager.GetString("Check_Holiday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนชม.ที่ชดเชยไม่ควร 4 ชม.กรุณาตรวจสอบด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Hour() As String
            Get
                Return ResourceManager.GetString("Check_Hour", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณากำหนดจำนวนชั่วโมง OT ด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Config_OT() As String
            Get
                Return ResourceManager.GetString("Config_OT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่สามารถแก้ไขได้เนื่องจากวันที่นี้ ได้บันทึกไปแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Edit_Failed_spacial_holiday() As String
            Get
                Return ResourceManager.GetString("Edit_Failed_spacial_holiday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สร้างสคริปเสร็สแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Gen_Scrip_Complete() As String
            Get
                Return ResourceManager.GetString("Gen_Scrip_Complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันสุดท้ายน้อยกว่าวันที่เริ่มต้นกรุณากรอกใหม่.
        '''</summary>
        Friend Shared ReadOnly Property Insert_Data_Again() As String
            Get
                Return ResourceManager.GetString("Insert_Data_Again", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณไม่มีสิทธิ์เข้าใจโปรแกรม อาจเป็นเพราะ ชื่อผู้ใช้ หรือ รหัสผ่าน ไม่ถูกต้อง.
        '''</summary>
        Friend Shared ReadOnly Property login_user_password_fail() As String
            Get
                Return ResourceManager.GetString("login_user_password_fail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to นาทีนี้ถูกใช้แล้ว กรุณาเปลี่ยนใหม่.
        '''</summary>
        Friend Shared ReadOnly Property MS_In_Use() As String
            Get
                Return ResourceManager.GetString("MS_In_Use", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ยืนยันรหัสผ่านไม่ตรงกับรหัสผ่าน.
        '''</summary>
        Friend Shared ReadOnly Property password_notsame_confirmPassword() As String
            Get
                Return ResourceManager.GetString("password_notsame_confirmPassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to นำออกจากกลุ่มสิทธิ์เรียบร้อย.
        '''</summary>
        Friend Shared ReadOnly Property permission_exportdata() As String
            Get
                Return ResourceManager.GetString("permission_exportdata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชื่อกลุ่มซ้ำ.
        '''</summary>
        Friend Shared ReadOnly Property permission_groupsame() As String
            Get
                Return ResourceManager.GetString("permission_groupsame", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนชื่อกลุ่มสิทธิ์.
        '''</summary>
        Friend Shared ReadOnly Property permission_please_input_groupname() As String
            Get
                Return ResourceManager.GetString("permission_please_input_groupname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาดับเบิ้ลคลิ๊กกลุ่มสิทธิ์เพื่อทำการกำหนดกลุ่มสิทธิ์.
        '''</summary>
        Friend Shared ReadOnly Property permissionGroup_selectdata() As String
            Get
                Return ResourceManager.GetString("permissionGroup_selectdata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนชื่อบริษัท.
        '''</summary>
        Friend Shared ReadOnly Property please_input_companyname() As String
            Get
                Return ResourceManager.GetString("please_input_companyname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนเวลาเข้า.
        '''</summary>
        Friend Shared ReadOnly Property please_input_TimeIN() As String
            Get
                Return ResourceManager.GetString("please_input_TimeIN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกกะที่ต้องการกำหนด.
        '''</summary>
        Friend Shared ReadOnly Property please_select_ka_() As String
            Get
                Return ResourceManager.GetString("please_select_ka_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประมวลเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Procress_complete() As String
            Get
                Return ResourceManager.GetString("Procress_complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประมวลผล......
        '''</summary>
        Friend Shared ReadOnly Property Procress_label() As String
            Get
                Return ResourceManager.GetString("Procress_label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการปรับให้พ้นสภาพจากการเป็นพนักงานหรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property Quit_job() As String
            Get
                Return ResourceManager.GetString("Quit_job", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ข้อมูลนี้มีอยู่แล้วคุณต้องการเขียนข้อมูลทับหรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property repleace_Data() As String
            Get
                Return ResourceManager.GetString("repleace_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มีข้อมูลอยู่ในระหว่างช่วงที่กำหนด คุณต้องการเขียนข้อมูลทับหรือเปล่า.
        '''</summary>
        Friend Shared ReadOnly Property Repleace_Data_2() As String
            Get
                Return ResourceManager.GetString("Repleace_Data_2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันที่ :.
        '''</summary>
        Friend Shared ReadOnly Property Report_date_label() As String
            Get
                Return ResourceManager.GetString("Report_date_label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ช่วงเวลาเกิน 31 วัน กรุณาเลือกใหม่.
        '''</summary>
        Friend Shared ReadOnly Property Report_Overtime_31() As String
            Get
                Return ResourceManager.GetString("Report_Overtime_31", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกข้อมูลที่ต้องการค้นหาก่อนออกรายงาน.
        '''</summary>
        Friend Shared ReadOnly Property Report_Selectdata() As String
            Get
                Return ResourceManager.GetString("Report_Selectdata", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลได้เนื่องจากสิทธิในการลาหมด.
        '''</summary>
        Friend Shared ReadOnly Property Save_Failed() As String
            Get
                Return ResourceManager.GetString("Save_Failed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่สามารถบันทึกได้ เนื่องจากการกำหนด {วันที่ทำงานพิเศษ} ต้องไม่ตรงกับ {วันที่วันหยุดพิเศษ}.
        '''</summary>
        Friend Shared ReadOnly Property Save_Failed_spacial_holiday() As String
            Get
                Return ResourceManager.GetString("Save_Failed_spacial_holiday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่สามารถบันทึกข้อมูลได้เนื่องจากสิทธิในการลาหมด เนื่องจากช่วงเวลาที่กำหนดเกินสิทธิที่ได้กำหนดไว้.
        '''</summary>
        Friend Shared ReadOnly Property Save_Failed_Vacation() As String
            Get
                Return ResourceManager.GetString("Save_Failed_Vacation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกรูปแบบการคำนวณ OT ด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_Cal_OT() As String
            Get
                Return ResourceManager.GetString("Select_Cal_OT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกรายการที่ต้องการลบด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_Data_For_Del() As String
            Get
                Return ResourceManager.GetString("Select_Data_For_Del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกว่าจะเอา วันถัดไป หรือ จะเอาวันก่อนหน้า ให้เลือกอย่างใดอย่างหนึ่ง.
        '''</summary>
        Friend Shared ReadOnly Property Select_Day() As String
            Get
                Return ResourceManager.GetString("Select_Day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกรูปแบบการ GetText ด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_GetText() As String
            Get
                Return ResourceManager.GetString("Select_GetText", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกประเภทการลาด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_Type_Abs() As String
            Get
                Return ResourceManager.GetString("Select_Type_Abs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกประเภทการลาด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Select_Vacation() As String
            Get
                Return ResourceManager.GetString("Select_Vacation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ชื่อผู้ใช้งานนี้มีอยู่แล้ว.
        '''</summary>
        Friend Shared ReadOnly Property Username_same() As String
            Get
                Return ResourceManager.GetString("Username_same", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
