'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class res_warning_message
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.res_warning_message", GetType(res_warning_message).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to จำนวนที่ป้อนต้องไม่น้อยกว่า 0.
        '''</summary>
        Friend Shared ReadOnly Property amount_littel_zero() As String
            Get
                Return ResourceManager.GetString("amount_littel_zero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนเฉพาะตัวเลข.
        '''</summary>
        Friend Shared ReadOnly Property amount_please_input_number_only() As String
            Get
                Return ResourceManager.GetString("amount_please_input_number_only", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนเวลาให้ถูกต้อง.
        '''</summary>
        Friend Shared ReadOnly Property Check_day() As String
            Get
                Return ResourceManager.GetString("Check_day", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาเลือกเดือนด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Month() As String
            Get
                Return ResourceManager.GetString("Check_Month", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนเวลาให้ถูกต้อง.
        '''</summary>
        Friend Shared ReadOnly Property check_time() As String
            Get
                Return ResourceManager.GetString("check_time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนปีให้ถูกต้องด้วย.
        '''</summary>
        Friend Shared ReadOnly Property Check_Year() As String
            Get
                Return ResourceManager.GetString("Check_Year", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to คุณต้องการลบข้อมูลหรือไม่.
        '''</summary>
        Friend Shared ReadOnly Property Confirm_Del() As String
            Get
                Return ResourceManager.GetString("Confirm_Del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนตัวเลขให้ถูกต้อง.
        '''</summary>
        Friend Shared ReadOnly Property correct_number() As String
            Get
                Return ResourceManager.GetString("correct_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ลบข้อมูลเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property delete_complete() As String
            Get
                Return ResourceManager.GetString("delete_complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to แก้ไขเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property edit_complete() As String
            Get
                Return ResourceManager.GetString("edit_complete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนรหัสพนักงาน.
        '''</summary>
        Friend Shared ReadOnly Property Insert_EmpID() As String
            Get
                Return ResourceManager.GetString("Insert_EmpID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อน {0} ด้วย.
        '''</summary>
        Friend Shared ReadOnly Property please_input_1parameter() As String
            Get
                Return ResourceManager.GetString("please_input_1parameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อนวันที่ให้ถูกต้อง.
        '''</summary>
        Friend Shared ReadOnly Property please_input_date() As String
            Get
                Return ResourceManager.GetString("please_input_date", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรุณาป้อน {0} เป็นตัวเลขด้วย.
        '''</summary>
        Friend Shared ReadOnly Property please_input_number_1parameter() As String
            Get
                Return ResourceManager.GetString("please_input_number_1parameter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {0} ซ้ำ.
        '''</summary>
        Friend Shared ReadOnly Property Same_data() As String
            Get
                Return ResourceManager.GetString("Same_data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to บันทึกเรียบร้อยแล้ว.
        '''</summary>
        Friend Shared ReadOnly Property save_complete() As String
            Get
                Return ResourceManager.GetString("save_complete", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
