'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class res_month
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.res_month", GetType(res_month).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มกราคม.
        '''</summary>
        Public Shared ReadOnly Property m1() As String
            Get
                Return ResourceManager.GetString("m1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ตุลาคม.
        '''</summary>
        Public Shared ReadOnly Property m10() As String
            Get
                Return ResourceManager.GetString("m10", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to พฤศจิกายน.
        '''</summary>
        Public Shared ReadOnly Property m11() As String
            Get
                Return ResourceManager.GetString("m11", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ธันวาคม.
        '''</summary>
        Public Shared ReadOnly Property m12() As String
            Get
                Return ResourceManager.GetString("m12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กุมภาพันธ์.
        '''</summary>
        Public Shared ReadOnly Property m2() As String
            Get
                Return ResourceManager.GetString("m2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มีนาคม.
        '''</summary>
        Public Shared ReadOnly Property m3() As String
            Get
                Return ResourceManager.GetString("m3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เมษายน.
        '''</summary>
        Public Shared ReadOnly Property m4() As String
            Get
                Return ResourceManager.GetString("m4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to พฤษภาคม.
        '''</summary>
        Public Shared ReadOnly Property m5() As String
            Get
                Return ResourceManager.GetString("m5", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to มิถุนายน.
        '''</summary>
        Public Shared ReadOnly Property m6() As String
            Get
                Return ResourceManager.GetString("m6", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กรกฏาคม.
        '''</summary>
        Public Shared ReadOnly Property m7() As String
            Get
                Return ResourceManager.GetString("m7", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to สิงหาคม.
        '''</summary>
        Public Shared ReadOnly Property m8() As String
            Get
                Return ResourceManager.GetString("m8", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to กันยายน.
        '''</summary>
        Public Shared ReadOnly Property m9() As String
            Get
                Return ResourceManager.GetString("m9", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
