'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Public Class res_simple_label
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeAttendance.res_simple_label", GetType(res_simple_label).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (ทั้งหมด).
        '''</summary>
        Public Shared ReadOnly Property all() As String
            Get
                Return ResourceManager.GetString("all", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to เรียบร้อยแล้ว.
        '''</summary>
        Public Shared ReadOnly Property Completed() As String
            Get
                Return ResourceManager.GetString("Completed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันหยุด.
        '''</summary>
        Public Shared ReadOnly Property Hol() As String
            Get
                Return ResourceManager.GetString("Hol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to วันหยุด.
        '''</summary>
        Public Shared ReadOnly Property Holiday() As String
            Get
                Return ResourceManager.GetString("Holiday", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to นางสาว.
        '''</summary>
        Public Shared ReadOnly Property Miss() As String
            Get
                Return ResourceManager.GetString("Miss", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to นาย.
        '''</summary>
        Public Shared ReadOnly Property Mr() As String
            Get
                Return ResourceManager.GetString("Mr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to นาง.
        '''</summary>
        Public Shared ReadOnly Property Mrs() As String
            Get
                Return ResourceManager.GetString("Mrs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ไม่ได้กำหนดกะ.
        '''</summary>
        Public Shared ReadOnly Property noShift() As String
            Get
                Return ResourceManager.GetString("noShift", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประมวลผลขาดงาน.
        '''</summary>
        Public Shared ReadOnly Property Process_Absent() As String
            Get
                Return ResourceManager.GetString("Process_Absent", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประมวลผลสาย - ออกก่อน.
        '''</summary>
        Public Shared ReadOnly Property Process_Late() As String
            Get
                Return ResourceManager.GetString("Process_Late", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประมวลผล OT.
        '''</summary>
        Public Shared ReadOnly Property Process_OT() As String
            Get
                Return ResourceManager.GetString("Process_OT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ประมวลผลเวลาทำงาน.
        '''</summary>
        Public Shared ReadOnly Property Process_WorkingTime() As String
            Get
                Return ResourceManager.GetString("Process_WorkingTime", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
